site_name: Documentation Mille Nuits - SP2
site_author: Amine

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: fr
  palette: 
    primary: indigo
    accent: blue

nav:
  - Accueil: index.md
  - Mission 1 - Documentation:
      - Comparatif Editeurs: mission1/comparatif.md
      - Installation MkDocs: mission1/installMk.md
  - Mission 2 - Postes Clients:
      - Masterisation: mission2/master.md
  - Mission 3 - Déploiement:
      - Comparatif Solutions: mission3/comparatif.md
      - Solution FOG: mission3/fog.md
  - Mission 4 - Incidents:
      - Outil GLPI: mission4/glpi.md
      - Procédures: mission4/procedures.md
